[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30305
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"

[rpc]
port = 8549
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts","signer"]
interface = "all"
cors = ["all"]

[websockets]
disable = false
port = 10548
interface = "all"
origins = ["none"]
apis = ["all"]
#apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc"]
hosts = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0xe15d3dfeaf14d9d21610ded574e8019b21393673"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
