


[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30308
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"
discovery = false

[rpc]
port = 8552
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts","signer"]
interface = "0.0.0.0"
cors = ["all"]

[websockets]
disable = false
port = 10546
interface = "all"
origins = ["none"]
apis = ["all"]
#apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc"]
hosts = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0x2eaf8d2c4a8547e67c7a8bc5acd72bed4100d87f"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
