

[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30306
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"
discovery = false

[rpc]
port = 8550
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts","signer"]
interface = "0.0.0.0"
cors = ["all"]

[websockets]
disable = false
port = 10549
interface = "all"
origins = ["none"]
apis = ["all"]
#apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc"]
hosts = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0x905c6721b85ccecd9dd44535055dacf18ebee551"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
